[features]
seeds = false
skip-lint = false
[programs.localnet]
image_writer = "8butU6ZgzAubbaXisbsGPc5sZF9FagNuuNZYepiKLtxi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sean/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
